import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Sparkles } from "lucide-react";

import { Topbar } from "@/components/layout/Topbar";
import { Card, CardHeader } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { EmptyState, LoadingState } from "@/components/ui/States";
import { listDatasets } from "@/api/datasets";
import { listInterpretations } from "@/api/ai";
import { formatRelativeFromNow } from "@/lib/utils";

export function AIPage() {
  const { data: datasets } = useQuery({
    queryKey: ["datasets", { page: 1, page_size: 50 }],
    queryFn: () => listDatasets({ page: 1, page_size: 50 }),
  });

  return (
    <>
      <Topbar crumbs={[{ label: "AI" }]} />
      <PageHeader
        title="AI"
        description="Model summaries, one per dataset run."
      />
      <div className="p-6">
        <Card>
          <CardHeader
            eyebrow="Catalogue"
            title="Latest interpretations"
            description="AI summaries generated by the backend pipeline."
          />
          <div className="mt-4 -mx-5">
            {!datasets ? (
              <LoadingState label="Loading datasets…" />
            ) : datasets.items.length === 0 ? (
              <EmptyState title="No datasets yet" description="Upload a dataset to surface AI interpretations." />
            ) : (
              <div className="divide-y divide-ink-100">
                {datasets.items.map((d) => (
                  <DatasetInterpretationRow key={d.id} datasetId={d.id} name={d.name} />
                ))}
              </div>
            )}
          </div>
        </Card>
      </div>
    </>
  );
}

function DatasetInterpretationRow({ datasetId, name }: { datasetId: string; name: string }) {
  const { data, isLoading } = useQuery({
    queryKey: ["interpretations", datasetId],
    queryFn: () => listInterpretations(datasetId, 1, 1),
  });
  const latest = data?.items[0];
  return (
    <div className="px-5 py-3">
      <div className="flex items-center justify-between">
        <Link to={`/datasets/${datasetId}`} className="text-sm font-medium text-ink-900 hover:text-brand-600">
          {name}
        </Link>
        {latest && <span className="text-xs text-ink-500">{formatRelativeFromNow(latest.created_at)}</span>}
      </div>
      <div className="mt-2 text-sm text-ink-600">
        {isLoading ? (
          <span className="text-ink-500">Loading…</span>
        ) : latest ? (
          <div className="flex items-start gap-2">
            <Sparkles className="mt-0.5 h-4 w-4 text-brand-500" />
            <p>{latest.summary}</p>
          </div>
        ) : (
          <span className="text-ink-500">No interpretation yet</span>
        )}
      </div>
    </div>
  );
}
